# Generated by Django 2.2.3 on 2019-07-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_code', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='detail',
            field=models.TextField(default='NULL'),
        ),
    ]
